title: Amanullah Khan # your name (or website title) here
logo: "images/Aman DP Dec22.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  First description 
  I am an AI-enabled Data Analyst and Strategy Consultant with a passion for using data to drive strategic decision-making and boost resource efficiency. With a proven track record in leading global organizations, I excel in effectively communicating insights and leading by example.
  <br><br>
  Second description 
  I am always open to connecting with new people and listening to fresh ideas. I thrive on collaboration and believe in the power of data-driven decision-making to propel businesses forward. With a strong commitment to staying at the forefront of industry trends, I hold certifications in Data Analysis with R Programming and Google Data Analytics Specialization.
  <br><br>
  <a href="https://www.linkedin.com/in/amanullahkhan9093/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: G-BLCYZ8M4H2 # your Google Analytics tracking ID here
